DROP DATABASE IF EXISTS `UserList`;

CREATE SCHEMA IF NOT EXISTS `UserList` DEFAULT CHARACTER SET utf8 ;
USE `UserList` ;

CREATE TABLE IF NOT EXISTS `UserList`.`UserList` (
  `Id` int(11) unsigned NOT NULL auto_increment,
  `FirstName` varchar(45) default NULL,
  `LastName` varchar(45) default NULL,
  `Email` varchar(255) default NULL,
  `Age` int default NULL,
  `Gender` varchar(45) default NULL,
  PRIMARY KEY (`Id`))

ENGINE = InnoDB;

INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Yoko","Green","tincidunt.aliquam@Quisqueimperdiet.org",31,"Male"),("Harding","Wagner","massa@orciquislectus.co.uk",27,"Female"),("Cain","Beck","nunc.est.mollis@sit.org",37,"Female"),("Mechelle","Martinez","nec.tempus.mauris@Morbiquis.com",19,"Female"),("Herman","Holloway","lorem.eu.metus@elitpretiumet.org",46,"Female"),("Yael","Hurst","Sed.id@interdumlibero.net",21,"Female"),("Roth","Diaz","non@enim.edu",73,"Female"),("Dora","Stanley","sem.elit@sitametdiam.co.uk",49,"Male"),("Elmo","Harris","Nam.ac@vel.org",56,"Male"),("Marny","Finch","at.arcu.Vestibulum@utlacusNulla.co.uk",33,"Male");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Tyler","Tyler","scelerisque.scelerisque@arcu.co.uk",44,"Male"),("Herrod","French","tincidunt.Donec@blanditmattis.edu",23,"Male"),("Vladimir","Shepard","tristique.senectus@Donec.net",20,"Male"),("Lareina","Kane","adipiscing@Proin.net",80,"Male"),("Ciara","Moon","commodo.hendrerit@neque.net",43,"Female"),("Kitra","Fernandez","malesuada.vel@posuerecubilia.com",48,"Male"),("Ariel","Klein","ac.turpis.egestas@mauris.ca",72,"Male"),("Carl","Arnold","morbi.tristique.senectus@turpisegestasAliquam.co.uk",80,"Male"),("Odysseus","Foley","ultrices@vitae.edu",87,"Male"),("Farrah","Mccall","nec@duiaugue.net",46,"Male");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Hermione","Mcknight","facilisis.magna@cursusnon.ca",33,"Male"),("Yoshio","Pruitt","scelerisque.sed.sapien@elementumloremut.org",44,"Male"),("Caryn","West","diam.eu.dolor@sagittis.co.uk",86,"Female"),("Damian","Hubbard","Donec.egestas.Duis@Nunclaoreet.co.uk",67,"Female"),("Anika","Schneider","urna.et@turpisnon.com",34,"Male"),("Troy","Dean","in@dapibusquam.ca",28,"Male"),("Ina","Ramsey","dictum.mi.ac@Donec.com",76,"Male"),("Odessa","Larsen","auctor@ante.co.uk",21,"Male"),("Ira","Savage","vel@atpede.ca",68,"Male"),("Quinn","Adkins","porttitor.scelerisque@lobortistellusjusto.com",84,"Female");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Abdul","Hoover","eu.ligula@ultrices.edu",60,"Male"),("Hayes","Haney","amet.ante.Vivamus@a.org",67,"Male"),("Kirestin","Shepard","mauris.sit.amet@morbitristiquesenectus.net",64,"Female"),("Destiny","Ferguson","gravida@eueuismod.co.uk",27,"Male"),("Hector","Rodriquez","molestie.tellus.Aenean@eutemporerat.ca",59,"Male"),("Shellie","Davenport","justo.Proin.non@auguescelerisque.org",55,"Female"),("Howard","Cobb","arcu@tellussemmollis.ca",21,"Female"),("Daniel","Boyle","tincidunt@ornarefacilisiseget.ca",53,"Female"),("Dolan","Lyons","turpis.Nulla.aliquet@estac.ca",23,"Female"),("Kirsten","Willis","fringilla.porttitor.vulputate@lectusquismassa.ca",42,"Male");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Bryar","Carter","aliquet.molestie.tellus@venenatis.co.uk",18,"Male"),("Luke","Mueller","est@sem.org",59,"Female"),("Wallace","Moran","Donec.sollicitudin@et.co.uk",53,"Female"),("Amery","Bryan","blandit.congue@eulacus.net",52,"Male"),("Jared","Duncan","nec@velitSed.co.uk",49,"Male"),("Merrill","Kirk","blandit.enim.consequat@ut.edu",26,"Male"),("Moana","Garrett","Aenean.sed@et.edu",53,"Male"),("Lara","Dominguez","blandit.viverra.Donec@sedduiFusce.edu",69,"Female"),("Gil","Cooper","nonummy@magnis.edu",73,"Male"),("Knox","Barnes","Nullam.velit@vitaerisusDuis.edu",68,"Male");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Nicole","Irwin","nostra@tempor.com",60,"Female"),("Ivan","Finley","Vivamus@montesnasceturridiculus.com",60,"Male"),("Scarlett","Valenzuela","tincidunt.vehicula@non.com",46,"Male"),("Gwendolyn","Hunt","Duis@placerat.ca",87,"Female"),("Brian","Moon","lacus.varius@eget.edu",87,"Female"),("Rhea","Ellis","a@Nunclectuspede.ca",71,"Female"),("Wayne","Brown","parturient.montes@massaMaurisvestibulum.net",27,"Male"),("Caldwell","Wyatt","Nam@lectus.ca",87,"Male"),("Lacy","Thomas","sed.facilisis@sollicitudin.com",41,"Male"),("Cassidy","Pickett","rhoncus.id.mollis@dictumplacerataugue.co.uk",31,"Female");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Cheyenne","Fitzpatrick","mauris.eu@ipsumporta.edu",63,"Female"),("Zahir","Burris","vestibulum@Namtempor.com",72,"Female"),("Hamish","Lambert","Donec.egestas@nec.org",36,"Female"),("Adria","Morton","vulputate.lacus@nibhsitamet.com",53,"Female"),("Xander","Lawson","ultrices.sit@auctorvitae.co.uk",30,"Male"),("Isaac","Ochoa","arcu.Aliquam.ultrices@elitEtiamlaoreet.net",76,"Male"),("Odysseus","Williams","netus.et.malesuada@dapibusligula.edu",28,"Female"),("Melanie","Ramsey","amet@Nullaegetmetus.org",31,"Male"),("Gregory","Vincent","metus.In@tempordiam.com",35,"Male"),("Lydia","Hansen","orci.lacus.vestibulum@enim.ca",27,"Male");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Echo","Bruce","laoreet.posuere.enim@mieleifendegestas.org",78,"Female"),("Blaine","Ingram","sed@Nunc.co.uk",42,"Male"),("Amal","Roberts","in.sodales.elit@ultrices.ca",45,"Male"),("Lynn","Stokes","sociis.natoque@dolorelit.net",20,"Female"),("Michael","French","lacus.Ut.nec@malesuadavelvenenatis.ca",87,"Female"),("Dustin","Michael","sapien.cursus@ac.net",19,"Male"),("Xaviera","Acevedo","eget.laoreet.posuere@neceuismodin.com",62,"Male"),("Timon","Kelly","luctus.ipsum.leo@necmetusfacilisis.net",79,"Female"),("Emi","Phelps","amet.dapibus@risus.ca",27,"Female"),("Wayne","Delaney","facilisis.eget@venenatis.edu",24,"Female");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Leroy","Mayer","mattis.ornare.lectus@malesuadafames.org",30,"Female"),("Malcolm","Sparks","ac.turpis.egestas@nonjustoProin.co.uk",60,"Male"),("Jayme","Munoz","Proin@Etiam.ca",81,"Female"),("Kylan","Pena","Quisque.tincidunt@ornareliberoat.com",34,"Female"),("Victoria","Lucas","ante.lectus.convallis@mi.com",86,"Female"),("Thaddeus","Randall","vitae.odio@Maecenas.edu",51,"Female"),("Louis","Hyde","lorem@temporeratneque.edu",71,"Female"),("Darryl","Rios","tempor.est.ac@velfaucibusid.com",23,"Female"),("Amanda","Mayo","est.mauris.rhoncus@fermentumconvallisligula.net",89,"Female"),("Jasmine","Dotson","Nulla@sodales.co.uk",48,"Female");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Fulton","Carpenter","vel.pede.blandit@laoreet.co.uk",81,"Male"),("Murphy","Riley","Duis.gravida@iaculisneceleifend.net",59,"Female"),("Kareem","Haney","nisi@Sedetlibero.com",56,"Female"),("Jakeem","Moss","nec.diam.Duis@congueIn.edu",29,"Female"),("Vladimir","Holloway","vel.quam@Aliquamgravidamauris.ca",64,"Male"),("Ila","Whitney","lectus.ante.dictum@Aliquamtincidunt.net",44,"Female"),("Reed","Burch","libero.Morbi.accumsan@Morbi.org",74,"Male"),("Belle","Ingram","rhoncus.Donec@diamvelarcu.edu",29,"Female"),("Zahir","Rodriguez","magna@vitaeodio.co.uk",27,"Female"),("Sonia","Fuller","Nulla.aliquet.Proin@auctor.com",44,"Female");
INSERT INTO `UserList` (`FirstName`,`LastName`,`Email`,`Age`,`Gender`) VALUES ("Echo","Carpenter","echo.pede.blandit@laoreet.co.uk",41,"Male"),("Murphy","Sparks","Sparks.gravida@iaculisneceleifend.net",51,"Female"),("Kareem","West","West@Sedetlibero.com",57,"Female"),("Jakeem","Pena","nec.diam.Duis@congueIn.edu",19,"Male"),("Vladimir","Moon","Moon.quam@Aliquamgravidamauris.ca",44,"Male");